<div class="carousel w-screen max-w-none overflow-x-auto flex flex-row" id="autoCarousel">
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/2-colares-com-pingente.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/bracelete-flores.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/brinco-algema.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/pulseira-colar-anel.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/tornozeleira-pe-sujo.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/brinco-pequeno-medio-grande.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/pulseira-torre-eiffell.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/colar-bonitinho.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/corrente-de-estrela.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/3-pulseiras.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/ane-caroline.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/brinco-na-ruiva.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/coracoes-entrelacados.jpeg" alt="Pizza" />
    </div>
    <div class="carousel-item flex-shrink-0">
        <img class="w-[300px] h-[200px]" src="/assets/images/correntes-grossas-e finas.jpeg" alt="Pizza" />
    </div>
</div>

<div class="max-w-screen-xl mx-auto">
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
        <div class="bg-white shadow-md rounded-xl p-6">
            <div class="card bg-base-100 w-96 shadow-sm">
                <figure>
                    <img class="h-[500px]"
                        src="/assets/images/ane-caroline.jpeg"
                        alt="Shoes" />
                </figure>
                <div class="card-body">
                    <h2 class="card-title mt-2">
                        Conjunto pulseira e brinco
                        <div class="badge badge-secondary">Preço: R$ 6000,00</div>
                    </h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, reprehenderit.</p>
                    <div class="card-actions justify-end">
                        <div class="badge badge-outline">Prata</div>
                        <div class="badge badge-outline">ouro fino</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-white shadow-md rounded-xl p-6">
            <div class="card bg-base-100 w-96 shadow-sm">
                <figure>
                    <img class="h-[500px]"
                        src="/assets/images/aneis-prata-algema.jpeg"
                        alt="Shoes" />
                </figure>
                <div class="card-body">
                    <h2 class="card-title">
                        Card Title
                        <div class="badge badge-secondary">NEW</div>
                    </h2>
                    <p>A card component has a figure, a body part, and inside body there are title and actions parts</p>
                    <div class="card-actions justify-end">
                        <div class="badge badge-outline">Fashion</div>
                        <div class="badge badge-outline">Products</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-white shadow-md rounded-xl p-6">
            <div class="card bg-base-100 w-96 shadow-sm">
                <figure>
                    <img class="h-[500px] w-full"
                        src="/assets/images/bracelete-pandora.jpeg"
                        alt="Shoes" />
                </figure>
                <div class="card-body">
                    <h2 class="card-title">
                        Card Title
                        <div class="badge badge-secondary">NEW</div>
                    </h2>
                    <p>A card component has a figure, a body part, and inside body there are title and actions parts</p>
                    <div class="card-actions justify-end">
                        <div class="badge badge-outline">Fashion</div>
                        <div class="badge badge-outline">Products</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-white shadow-md rounded-xl p-6">
            <div class="card bg-base-100 w-96 shadow-sm">
                <figure>
                    <img
                        src="https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp"
                        alt="Shoes" />
                </figure>
                <div class="card-body">
                    <h2 class="card-title">
                        Card Title
                        <div class="badge badge-secondary">NEW</div>
                    </h2>
                    <p>A card component has a figure, a body part, and inside body there are title and actions parts</p>
                    <div class="card-actions justify-end">
                        <div class="badge badge-outline">Fashion</div>
                        <div class="badge badge-outline">Products</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-white shadow-md rounded-xl p-6">
            <div class="card bg-base-100 w-96 shadow-sm">
                <figure>
                    <img
                        src="https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp"
                        alt="Shoes" />
                </figure>
                <div class="card-body">
                    <h2 class="card-title">
                        Card Title
                        <div class="badge badge-secondary">NEW</div>
                    </h2>
                    <p>A card component has a figure, a body part, and inside body there are title and actions parts</p>
                    <div class="card-actions justify-end">
                        <div class="badge badge-outline">Fashion</div>
                        <div class="badge badge-outline">Products</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-white shadow-md rounded-xl p-6">
            <div class="card bg-base-100 w-96 shadow-sm">
                <figure>
                    <img
                        src="https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp"
                        alt="Shoes" />
                </figure>
                <div class="card-body">
                    <h2 class="card-title">
                        Card Title
                        <div class="badge badge-secondary">NEW</div>
                    </h2>
                    <p>A card component has a figure, a body part, and inside body there are title and actions parts</p>
                    <div class="card-actions justify-end">
                        <div class="badge badge-outline">Fashion</div>
                        <div class="badge badge-outline">Products</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>