<div class="flex justify-center">
    <fieldset class="fieldset w-[600px] bg-base-200 border-base-300 flex flex-col grid justify-items-center rounded-box border p-4 mt-[200px]">

        <label class="label mt-5 mb-5">Email</label>
        <input type="email" placeholder="Digite seu email" class="primary" />


        <label class="label mt-5 mb-5">Password</label>
        <input type="password" placeholder="Digite sua senha" class="input input-accent" />


        <button class="btn btn-neutral mt-4">Login</button>
    </fieldset>
</div>