 <div class="container flex justify-content-center mt-5">
     <form action="update.php" method="POST" class="<?= $product->hasErrors() ? '' : 'was-validated' ?>" novalidate>
         <input type="hidden" name="_method" value="PUT" />
         <input type="hidden" name="product[id]" value="<?= $product->getId() ?>" />
         <div>
             <label for="product_name" class="form-label">Nome do produto</label>
             <input type="text" name="product[name]" class="form-control" id="product_name" value="<?= $product->getName() ?>" placeholder="Bracelete, colar, anel, etc.." required />
             <div class="invalid-feedback"><?= $product->getErrors('name') ? $product->getErrors('name') : '' ?></div>
         </div>
         <button type="submit" class="btn btn-primary mt-5">Atualizar</button>
     </form>
 </div>