<div class="row row-cols-1 row-cols-md-3 g-4">
    <?php foreach ($products as $index => $product): ?>
        <div class="col">
            <div class="card h-100">
                <img src="/assets/images/bracelete.jpeg" class="card-img-top" style="height: 20rem;" alt="Imagem do produto">
                <div class="card-body">
                    <h5 class="card-title"><?= htmlspecialchars($product) ?></h5>
                    <p class="card-text">Descrição placeholder.</p>
                    <div class="d-flex justify-content-evenly">
                        <a href="/pages/products/show.php?id=<?= $index ?>" class="btn btn-primary">Detalhes</a>
                        <a href="/pages/products/edit.php?id=<?= $index ?>" class="btn btn-primary">Atualizar</a>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>