<div>
    <h1><?= $product->getName() ?></h1>
    <div class="container mt-5 flex justify-content-center">
        <div class="card" style="width: 18rem;">
            <img src="/assets/images/bracelete.jpeg" class="card-img-top" alt="Imagem do produto">
            <div class="card-body">
                <h5 class="card-title"><?= $product->getName() ?></h5>
                <p class="card-text">Descrição placeholder.</p>
            </div>
        </div>
    </div>
</div>