name: Continuous Integration
on:
  push:
    branches:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Composer install
        run: ./run composer install

      - name: PHPUnit
        run: ./run test

code_quality:
  name: Code Quality checkout
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Composer install
      run: ./run composer install

    - name: PHPCS
      run: ./run phpcs

    - name: PHPStan
      run: ./run phpstan
